export enum STATUS {
  COMING_UP = 'COMING_UP',
  ACTIVE_HEALTHY = 'ACTIVE_HEALTHY',
  ACTIVE_UNHEALTHY = 'ACTIVE_UNHEALTHY',
  GOING_DOWN = 'GOING_DOWN',
  INACTIVE = 'INACTIVE',
  REMOVED = 'REMOVED',
}
