name: Example workflow that triggers tests run in this repo

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: repository_dispatch event_type
        required: true
        options:
          - run-integration-local
          - run-verification-prod
          - run-verification-stage

jobs:
  run-tests:
    name: Run tests from another repo
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Wait until your code is published or deployed
        run: echo "Waiting for deployment to finish..."

      - name: Emit repository_dispatch to tests repo
        uses: mvasigh/dispatch-action@main
        with:
          # You should provide either:
          # * Personal access tokens with repo scope. For more information, see
          #     "https://docs.github.com/articles/creating-a-personal-access-token-for-the-command-line".
          # * GitHub Apps with both metadata:read and contents:read&write permissions.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: tests
          owner: supabase
          event_type: ${{ github.event.inputs.name }} # 'run-integration-local', 'run-verification-prod', 'run-verification-stage'
          # result will be posted to #test-alerts channel if tests fail
