name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      url:
        description: supabase dashboard url
        required: true

      platform_uri:
        type: choice
        description: api uri for platform 1. io - prod 2. green - stage
        required: true
        options:
          - 'https://api.supabase.io/platform'
          - 'https://api.supabase.green/platform'

      node_env:
        type: choice
        required: true
        options:
          - prod
          - staging

      project_ref:
        type: choice
        description: project ref for tests 1. bwh - prod 2. hwm - stage
        required: true
        options:
          - bwhmrdxxwjfmrelopnji
          - hwmqcqbzihriioxfvgvr

      view_id:
        type: choice
        description: view id for tests 1. 28630 - prod 2. 28654 - stage
        required: true
        options:
          - '28630'
          - '28654'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test -c ./frontend/playwright.config.ts
        env:
          CI: true
          NODE_ENV: ${{ github.event.inputs.node_env }}
          GITHUB_TOTP: ${{ secrets.VERIFICATION_PROD_GITHUB_TOTP }}
          GITHUB_USER: ${{ secrets.VERIFICATION_PROD_GITHUB_USER }}
          GITHUB_PASS: ${{ secrets.VERIFICATION_PROD_GITHUB_PASS }}
          SUPA_DASHBOARD: ${{ github.event.inputs.url }}
          SUPA_PLATFORM_URI: ${{ github.event.inputs.platform_uri }}
          FE_TESTS_PROJECT_REF: ${{ github.event.inputs.project_ref }}
          FE_TESTS_PROJECT_NAME: 'frontend-tests'
          FE_TESTS_ACTOR_INFO_VIEW_ID: ${{ github.event.inputs.view_id }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
