name: Run verification tests against production env

on:
  schedule:
    - cron: '0 4/8 * * *'
  # Webhook to trigger the workflow from other repositories
  repository_dispatch:
    types: [run-verification-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  GITHUB_TOTP: ${{ secrets.VERIFICATION_PROD_GITHUB_TOTP }}
  GITHUB_USER: ${{ secrets.VERIFICATION_PROD_GITHUB_USER }}
  GITHUB_PASS: ${{ secrets.VERIFICATION_PROD_GITHUB_PASS }}
  SUPA_PLATFORM_URI: 'https://api.supabase.io/platform'
  SUPA_DASHBOARD: 'https://supabase.com/dashboard'
  SUPA_META_URI: 'https://api.supabase.io/platform/pg-meta'

jobs:
  verification:
    name: Verification Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: verification

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Create results folder
        run: mkdir -p allure-results

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Install dependencies
        run: npm ci

      - name: Run verification tests
        run: npm run test:prod
        env:
          PROJECT_REF: 'nhspkocxnkjvbphkoepx'
          PROJECT_NAME: 'verifytests'
          SUPA_ORG_SLUG: 'squealing-ivory-qshl8px'
          PROJECT_DB_PASS: ${{ secrets.VERIFICATION_PROD_PROJECT_DB_PASS }}
          SUPA_PROJECT_DOMAIN: 'supabase.co'
          HUBSPOT_API_KEY: ${{ secrets.VERIFICATION_PROD_HUBSPOT_API_KEY }}

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: allure-results-verification-prod
          path: verification/allure-results
          retention-days: 1

  integration:
    name: Integration Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    env:
      SUPA_PLATFORM_URI: 'https://api.supabase.io/v0'
      SUPA_V0_KEY: ${{ secrets.VERIFICATION_PROD_V0_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create project
        env:
          SUPA_ORG_ID: '105764'
          OUTPUT_FILE: '.env.migrate'
          PROJECT_JSON: 'project.json'
          SLEEP_SECS: '150'
        run: |
          npm run project:create:v0
          cp .env.migrate integration/.env.prod
          cp .env.migrate restore/.env.prod
          npm run project:migrate
          echo $(cat project.json | jq -r ".ref")

      - name: Install dependencies
        run: npm ci
        working-directory: integration

      - name: Create results folders
        run: |
          mkdir -p integration/allure-results
          mkdir -p restore/allure-results

      - name: Run integration tests
        run: npm run test:prod
        working-directory: integration
        env:
          CLEANUP_USERS: false

      - name: Install dependencies (restore tests)
        run: npm ci
        working-directory: restore

      - name: Run restore tests preparation
        run: npm run prepare:prod
        working-directory: restore

      - name: Pause and restore project
        id: pause
        continue-on-error: true
        run: npm run project:restore:v0
        env:
          PROJECT_JSON: 'project.json'

      - name: Notify slack
        uses: rtCamp/action-slack-notify@v2
        if: steps.pause.outcome == 'failure'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: TestBot
          SLACK_ICON_EMOJI: ':supa-eve:'
          SLACK_LINK_NAMES: true
          SLACK_TITLE: 'Prod Verification tests Failed'
          SLACK_FOOTER: 'Supabase'
          SLACK_COLOR: failure
          SLACK_MESSAGE: 'Hey : Verification tests for Prod have finished with failure, cause project was not paused in time. <https://supabase.github.io/test-reports/verification-prod/${{ github.run_number }}|See the report>'

      - name: Cancel if project was not paused
        if: steps.pause.outcome == 'failure'
        run: exit 1

      - name: Run restore tests
        run: npm run test:prod
        working-directory: restore

      - name: Integration tests second run
        run: npm run test:prod
        working-directory: integration

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: allure-results-integration-prod
          path: integration/allure-results
          retention-days: 1

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: allure-results-restore-prod
          path: restore/allure-results
          retention-days: 1

      - name: Remove project
        run: npm run project:delete:v0
        if: ${{ always() }}
        env:
          PROJECT_JSON: 'project.json'

      - name: Alert slack if tests failed but not if project was not paused
        if: ${{ failure() }} && steps.pause.outcome != 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: TestBot
          SLACK_ICON_EMOJI: ':supa-eve:'
          SLACK_LINK_NAMES: true
          SLACK_TITLE: 'Prod Verification tests Failed'
          SLACK_FOOTER: 'Supabase'
          SLACK_COLOR: failure
          SLACK_MESSAGE: 'Hey @group-infra : Verification tests for Prod have finished with failure. <https://supabase.github.io/test-reports/verification-prod/${{ github.run_number }}|See the report>'

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run frontend tests
        run: npm run test:frontend:ci:prod
        env:
          FE_TESTS_PROJECT_REF: 'bwhmrdxxwjfmrelopnji'
          FE_TESTS_PROJECT_NAME: 'frontend-tests'
          FE_TESTS_PROJECT_DB_PASS: ${{ secrets.VERIFICATION_PROD_FE_TESTS_PROJECT_DB_PASS }}
          FE_TESTS_ACTOR_INFO_VIEW_ID: '29313'
          SUPA_PROJECT_DOMAIN: 'supabase.co'

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: playwright-report-frontend-stage
          path: frontend/playwright-report/
          retention-days: 7

  report:
    name: Upload report
    if: ${{ always() }}
    needs: [verification, integration]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Download all test results
        uses: actions/download-artifact@v3

      - name: CP all results to the one folder
        shell: bash
        run: |
          mkdir ./allure-results
          cp ./allure-results-integration-prod/* ./allure-results/
          cp ./allure-results-restore-prod/* ./allure-results/
          cp ./allure-results-verification-prod/* ./allure-results/

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          repository: supabase/test-reports
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          github_repo: test-reports
          allure_results: allure-results
          allure_history: allure-history
          subfolder: verification-prod
          keep_reports: 50

      - name: Deploy report to Github Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: supabase/test-reports
          ssh-key: ${{ secrets.DEPLOY_TO_TEST_REPORTS_KEY }}
          branch: gh-pages
          folder: allure-history
          force: false
