name: Run frontend tests against production env

on:
  # Webhook to trigger the workflow from other repositories
  repository_dispatch:
    types: [run-frontend-tests-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  GITHUB_TOTP: ${{ secrets.VERIFICATION_PROD_GITHUB_TOTP }}
  GITHUB_USER: ${{ secrets.VERIFICATION_PROD_GITHUB_USER }}
  GITHUB_PASS: ${{ secrets.VERIFICATION_PROD_GITHUB_PASS }}
  SUPA_PLATFORM_URI: 'https://api.supabase.io/platform'
  SUPA_META_URI: 'https://api.supabase.io/platform/pg-meta'
  SUPA_DASHBOARD: 'https://supabase.com/dashboard'

jobs:
  verification:
    name: Verification Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: verification

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Install dependencies
        run: npm ci

      - name: Run verification tests
        run: npm run test:prod
        env:
          PROJECT_REF: 'nhspkocxnkjvbphkoepx'
          PROJECT_NAME: 'verifytests'
          SUPA_ORG_SLUG: 'squealing-ivory-qshl8px'
          PROJECT_DB_PASS: ${{ secrets.VERIFICATION_PROD_PROJECT_DB_PASS }}
          SUPA_PROJECT_DOMAIN: 'supabase.co'
          HUBSPOT_API_KEY: ${{ secrets.VERIFICATION_PROD_HUBSPOT_API_KEY }}

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: allure-results-verification-prod
          path: verification/allure-results
          retention-days: 1

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run frontend tests
        run: npm run test:frontend:ci:prod
        env:
          FE_TESTS_PROJECT_REF: 'bwhmrdxxwjfmrelopnji'
          FE_TESTS_PROJECT_NAME: 'frontend-tests'
          FE_TESTS_PROJECT_DB_PASS: ${{ secrets.VERIFICATION_PROD_FE_TESTS_PROJECT_DB_PASS }}
          FE_TESTS_ACTOR_INFO_VIEW_ID: '29313'
          SUPA_PROJECT_DOMAIN: 'supabase.co'

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: playwright-report-frontend-stage
          path: frontend/playwright-report/
          retention-days: 7

  alert:
    name: Alert slack if tests failed
    if: ${{ failure() }}
    needs: [frontend, verification]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Notify slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: TestBot
          SLACK_ICON_EMOJI: ':supa-eve:'
          SLACK_LINK_NAMES: true
          SLACK_TITLE: 'Prod Frontend Verification tests Failed'
          SLACK_FOOTER: 'Supabase'
          SLACK_COLOR: failure
          SLACK_MESSAGE: 'Hey @group-frontend : Verification tests for Prod have finished with failure.'
